name: Build and Release Service Monitor

on:
  push:
    paths:
      - 'service_monitor.c'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            binary_name: service_monitor_x86_64
            gcc_package: gcc
            gpp_package: g++
            build_command: gcc -o service_monitor_x86_64 service_monitor.c
          - arch: i686
            binary_name: service_monitor_i686
            gcc_package: gcc-multilib
            gpp_package: g++-multilib
            build_command: gcc -m32 -o service_monitor_i686 service_monitor.c
          - arch: armv7
            binary_name: service_monitor_armv7
            gcc_package: gcc-arm-linux-gnueabihf
            gpp_package: g++-arm-linux-gnueabihf
            build_command: arm-linux-gnueabihf-gcc -o service_monitor_armv7 service_monitor.c
          - arch: aarch64
            binary_name: service_monitor_aarch64
            gcc_package: gcc-aarch64-linux-gnu
            gpp_package: g++-aarch64-linux-gnu
            build_command: aarch64-linux-gnu-gcc -o service_monitor_aarch64 service_monitor.c
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.gcc_package }} ${{ matrix.gpp_package }}

      - name: Build Service Monitor
        run: ${{ matrix.build_command }}

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: ./${{ matrix.binary_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Binary Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Git Tag
        id: create_tag
        run: |
          TAG_NAME=v$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          echo "::set-output name=tag::$TAG_NAME"

      - name: Push Tag
        run: |
          git push origin ${{ steps.create_tag.outputs.tag }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ steps.create_tag.outputs.tag }}
          body: |
            Automated release for Service Monitor.
            Built on ${{ github.ref }} by GitHub Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: ./binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}